name: Deploy
on:
  push:
    branches:
      - develop
      - main

jobs:
  Staging-Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Build Website
        run: |
          npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: dist
        run: |
          aws s3 sync . s3://class-rental-car-dev --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - name: Slack-Notification
        uses: slackapi/slack-github-action@v2.1.1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          swebhook-type: incoming-webhook
          payload: |
            text: ステージング環境にデプロイされました *Commit Message:* {{ github.event.head_commit.message || 'No commit message' }}*
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<http://class-rental-car-dev.s3-website-ap-northeast-1.amazonaws.com/|Staging ENV> from repository *{{ github.event.repository.name }}* by *{{ github.event.pusher.name }}*"
        if: success()

  Production-Deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Build Website
        run: |
          npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: S3 sync
        working-directory: dist
        run: |
          aws s3 sync . s3://class-rental-car.com --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - name: Slack-Notification
        uses: slackapi/slack-github-action@v2.1.1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          swebhook-type: incoming-webhook
          payload: |
            text: 本番環境にデプロイされました *Commit Message:* {{ github.event.head_commit.message || 'No commit message' }}*
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<http://class-rental-car-dev.com/|Production ENV> from repository *{{ github.event.repository.name }}* by *{{ github.event.pusher.name }}*"
        if: success()
